# Generated by Django 5.1.1 on 2024-10-22 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_user_is_doctor_user_is_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_hospital',
            field=models.BooleanField(default=False),
        ),
    ]
