# Generated by Django 5.1.1 on 2024-10-30 19:56

import first_app.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0009_alter_user_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', first_app.models.mymanager()),
            ],
        ),
    ]
