# Generated by Django 5.1.1 on 2024-11-04 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0015_alter_doctor_specialist'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='doctor_patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctors', models.ManyToManyField(related_name='my_patients', to='first_app.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_doctors', to='first_app.patient')),
            ],
        ),
    ]
