# Generated by Django 5.1.1 on 2024-11-04 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0016_doctor_likes_doctor_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctor_patient_liked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctors', models.ManyToManyField(related_name='liked_patients', to='first_app.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_doctors', to='first_app.patient')),
            ],
        ),
    ]
