# Generated by Django 5.1.1 on 2024-11-04 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0019_user_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='default.png', upload_to='patient_images/'),
        ),
    ]
