# Generated by Django 5.1.1 on 2024-11-07 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0021_user_groups_user_user_permissions_alter_user_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctors_advices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advice', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_advices', to='first_app.doctor')),
            ],
        ),
    ]
