# Generated by Django 5.1.3 on 2024-11-18 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0023_patient_pending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors_advices',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
