# Generated by Django 5.1.3 on 2024-11-18 21:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0025_massage'),
    ]

    operations = [
        migrations.AddField(
            model_name='massage',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender_massages', to=settings.AUTH_USER_MODEL),
        ),
    ]
